17b hackathon post
pharmaverse/comms_wg pull request #41
Opened 2023-06-16 13:51 UTC by StefanThoma

2023-06-19 13:41 UTC, StefanThoma commented
@bms63 Decided to write a review of the hackathon anyways...

2023-06-19 15:11 UTC, StefanThoma commented
This `Link` issue should be resolved once pull-request 17b is through (as the date-change will impact the url)

2023-06-19 20:27 UTC, kaz462 requested changes

2023-06-19 20:27 UTC, kaz462 commented on posts/2023-06-19_hackathon_writeup/index.qmd
> +We were really excited to see over **500** people from around 40 countries joining our *introduction to R workshop* in January!
```suggestion
We were really excited to see over **500** people from around 40 countries joining our *Introduction to R workshop* in January!
```

2023-06-19 20:27 UTC, kaz462 commented on posts/2023-06-19_hackathon_writeup/index.qmd
> +216 out of `r sum((introR$is_your_company_using_r_for_clinical_trial_data_analysis %>% table(useNA = "always"))[1:2])` confirmed that their company is already using R for clinial trial data analysis,
```suggestion
216 out of `r sum((introR$is_your_company_using_r_for_clinical_trial_data_analysis %>% table(useNA = "always"))[1:2])` confirmed that their company is already using R for clinical trial data analysis, the remaining 131 did not answer this question.
```

2023-06-19 20:27 UTC, kaz462 commented on posts/2023-06-19_hackathon_writeup/index.qmd
> +The target audience for this workshop were programmers who are very familiar with SAS, but not so familiar with R, our polls confirmed this.
```suggestion
The target audience for this workshop was programmers who are very familiar with SAS, but not so familiar with R, our polls confirmed this.
```

2023-06-19 20:27 UTC, kaz462 commented on inst/WORDLIST.txt
> +clinial
```suggestion
```

2023-06-20 10:13 UTC, StefanThoma commented
@cicdguy do you know why the CICD Links workflow fails? 
There are no errors due to failing links, I don't know where the error arises. 
Thanks!

2023-06-20 14:10 UTC, kaz462 approved these changes

2023-06-20 18:21 UTC, merged